Tencent/TNN

source/tnn/device/opencl/acc/opencl_cpu_adapter_acc.cc

- branch: master
- macOS
- compile error: `./build_android.sh`
```shell
/Users/code/dl-inference-benchmark/tnn/tnn/source/tnn/device/opencl/acc/opencl_cpu_adapter_acc.cc:169:13: error: use of undeclared identifier 'status'
status = blob_converter.ConvertFromMat(mat, param, command_queue);
^
/Users/code/dl-inference-benchmark/tnn/tnn/source/tnn/device/opencl/acc/opencl_cpu_adapter_acc.cc:175:13: error: use of undeclared identifier 'status'
status = blob_converter.ConvertFromMat(mat, param, command_queue);
^
/Users/code/dl-inference-benchmark/tnn/tnn/source/tnn/device/opencl/acc/opencl_cpu_adapter_acc.cc:179:12: error: use of undeclared identifier 'status'
return status;
^
[ 15%] Building CXX objec
```

[BUG] Fix use of undeclared identifier 'status‘’

---

test/flags.cc
test/flags.h
test/test.cc

Add two flags in TNNtest: in(input_name), is(input_shape). Now TNNtest can load NCNN model with input_name and input_shape.

TNNtest can load NCNN model with input_name and input_shape

---

include/tnn/core/macro.h
source/tnn/device/arm/acc/arm_pow_layer_acc.cc
source/tnn/device/metal/acc/metal_cpu_adapter_acc.mm
source/tnn/device/opencl/acc/opencl_cpu_adapter_acc.cc
tools/convert2tnn/caffe_converter/caffe2tnn.py
tools/convert2tnn/converter.py
tools/convert2tnn/onnx_converter/align_model.py
tools/convert2tnn/onnx_converter/onnx2tnn.py
tools/convert2tnn/tf_converter/tf2tnn.py
tools/convert2tnn/utils/checker.py
tools/convert2tnn/utils/cmd.py

1.  处理了onnx2tnn的日志系统，统一成和TNN一致的日志系统。
2. 统一了Convert2tnn中的日志系统，使用loggging替换前面的print输出，并提供了debug、info、warning以及error四级日志输出，默认输出info、warning和error信息。
目前convert2tnn的日志打印如下：

优化了convert2tnn中的日志输出

---

tools/onnx2tnn/src/core/onnx2tnn.cc
tools/onnx2tnn/src/core/onnx2tnn.h
tools/onnx2tnn/src/core/onnx_remove/onnx2tnn_remove_image_scaler.cc

针对ImageScaler 层做了特殊处理，将该算子删除。
转换之前的：
转换之后的：

[ONNX2TNN][BUG]1. fix issue #125;

---

source/tnn/interpreter/tnn/layer_interpreter/detection_output_interpreter.cc
source/tnn/utils/naive_compute.cc

(1) when interprating detection_output layer in ssd models, variance_encoded_in_target is parsed wrongly;
(2) when codetype=1, the GetCodeType function returns wrong result;

fix bugs in ssd model

---

source/tnn/device/arm/arm_blob_converter.cc

fix the wrong stepsize in arm cpu RGBA reverse kernel.
For the rgba data, the stepsize for consecutive channels should be 4 instead of 3

fix wrong stepsize in RGBA reverse kernel

---

source/tnn/device/metal/acc/deconvolution/metal_deconv_layer_common.mm
test/unit_test/layer_test/test_deconv_layer.cc

(1) fix a few bugs for metal deconvolution implementation
1) fix the bug in transforming weights: the data layout of weights in layer_resource is niohw instead of noihw;
2) fix the bug when group>1: add the group offset for weights and bias;
(2) add more configs in deconvoluton unit test
(3) pass the updated unit test

fix #198-incorrect deconvolution results for metal

---

test/unit_test/layer_test/test_deconv_layer.cc

(1) remove unnecessary deconvolution test cases;
(2) keep all deconvolution kernels covered under the new unit test;
(3) pass the new deconvolution unit test.

remove unnecessary test cases in deconvolution

---

source/tnn/core/default_network.cc
source/tnn/core/default_network.h

fix core dump when create instance with same network in multi-thread
issue, #259

[BUG] fix core dump when create instance with same network in threads

---

source/tnn/memory_manager/shared_memory_manager.cc

先释放内存，然后申请失败，导致其他共享Instance运行异常。

alloc first

---

source/tnn/device/opencl/acc/opencl_tan_layer_acc.cc

修复部分机型上OpenCL tan层计算错误的问题，android ut测试Pass

use sin and cos to fix tan calc error on some devices(such as LON-AL00)

---

scripts/build_ios.sh

xcode12为模拟器编译sdk时增加了arm64架构，导致与为iPhone编译的sdk合并时出现架构冲突问题。
在build_ios.sh中增加对xcode版本的判断，使用xcode12时，不为模拟器的arm64架构编译代码。

[iOS] fix iPhone and simulator arch conflicts with Xcode12

---

source/tnn/device/metal/metal_blob_converter.mm
test/unit_test/blob_converter_test.cc

Metal ConvertFromMat支持naive与arm的N8UC4 mat，可以在SetInputMat直接使用；
相应修改单元测试进行覆盖

[Metal] enable CPU N8UC4 Mat in metal ConvertFromMat

---

source/tnn/device/opencl/acc/opencl_pooling_layer_acc.cc
source/tnn/device/opencl/cl/pooling.cl

使用local memory优化OpenCL Pooing
速度测试结果：https://docs.qq.com/sheet/DVXFndE5uek10bkVx

[OPENCL] optimize pooling with fine-grained

---

source/tnn/device/opencl/cl/arg.cl
source/tnn/device/opencl/cl/signed_mul.cl
source/tnn/device/opencl/opencl_runtime.cc

Hotfix opencl select

---

source/tnn/core/default_network.cc

[BUG] fix leayer leak bug when layer init failed

---

source/tnn/device/arm/acc/arm_concat_layer_acc.cc
source/tnn/device/cpu/acc/cpu_concat_layer_acc.cc

per tensor quantconcat need rescale, not only memcpy: `res = val * input_scale / output_scale`

[QUANT][BUG] fix per tensor quantconcat error

---

source/tnn/device/metal/acc/metal_permute_layer_acc.metal
source/tnn/device/metal/acc/metal_permute_layer_acc.mm
test/unit_test/layer_test/test_permute_layer.cc

1、更新metal permute layer acc，支持nwhc形式；
2、在layer init时检查permute参数，对当前不支持的参数报错；
3、更新unit_test
相关issue: #666

[Metal][UPD] update metal permute

---

tools/convert2tnn/build.sh
tools/convert2tnn/utils/align_model.py
tools/onnx2tnn/onnx-converter/build.sh

[CONVERTER2TNN][UPD] 1. default do not clean build directory;

---

include/tnn/core/common.h
source/tnn/device/rknpu/convert/rknpu_reduce_mean_layer.cc
source/tnn/device/rknpu/convert/rknpu_utils.cc
source/tnn/device/rknpu/convert/rknpu_utils.h
source/tnn/device/rknpu/rknpu_model_interpreter.cc
source/tnn/device/rknpu/rknpu_network.cc
source/tnn/device/rknpu/rknpu_network.h
source/tnn/device/rknpu/tnn_impl_rknpu.cc
source/tnn/device/rknpu/tnn_impl_rknpu.h
test/flags.h
test/test_utils.cc

1. 传入tnn模型时，设置cache_path，可以生成cache model，编译时间长占用内存高
2. 第二次可以直接传入cache model，但需要设置model type为RKCHACHE

Patch rknpu cache

---

tools/convert2tnn/caffe_converter/caffe2tnn.py
tools/convert2tnn/converter.py
tools/convert2tnn/onnx_converter/onnx2tnn.py
tools/convert2tnn/tf_converter/tf2tnn.py
tools/convert2tnn/tflite_converter/tflite2tnn.py
tools/convert2tnn/utils/align_model.py
tools/convert2tnn/utils/args_parser.py
tools/convert2tnn/utils/cmd.py

1. 目前 TNN 的 converter2tnn 工具对 model_check的日志处理不好，当 model_check crash 之后不能获取对应的日志。
2. 目前 converter2tnn 使用 v1.0 作为默认的 version 信息，修改为当前时间。
3. 优化下 converter2tnn 的日志开关, 修改成为通过“-debug” 参数进行控制。

Dev issue 695

---

doc/cn/user/convert.md
doc/en/user/convert_en.md
tools/convert2tnn/tf_converter/tf2tnn.py
tools/convert2tnn/utils/args_parser.py

1. 修改了 Tensorflow 模型转换时 "-in" 参数的格式
older format:  -in="input1_name[1,128,128,3];input2_name[1,256,256,3]" 
new format： -in input1_name:1,128,128,3 input2_name:1,256,256,3
2. 更新了对应的文档

修改了 Tensorflow 模型转换时 "-in" 参数的格式

---

source/tnn/device/opencl/opencl_blob_converter.cc
source/tnn/device/opencl/opencl_blob_converter.h
source/tnn/device/opencl/opencl_utils.cc

1. NCHW Mat转换Blob，需要将参数的scale和bias 拷贝到设备端的clBuffer，解决方法: CPU缓存当前的scale和bias，只有scale和bias改变，才去做设备端的拷贝
2. 修复重复创建Kernel的问题
3. 使用Write/Read Buffer替换Map/UnMap+memcpy

[OPENCL] optimize blob converter scale bias copy && kernel create

---

source/tnn/device/cuda/cuda_context.cc
source/tnn/device/cuda/cuda_context.h

add field ``own_stream_`` to ``CudaContext``, indicating whether it owns the stream, so it can determine whether calling ``cudaStreamDestory`` or not on destructing.

implement ShareCommandQueue for CudaContext, so we can share stream

---

source/tnn/device/cuda/acc/cuda_group_norm_layer_acc.cu
source/tnn/network/tensorrt/layer_builder/group_norm_layer_builder.cc

Reimplement GN kernel:
1. support fp16 input
2. use float for accumulating for both fp16 & fp32 input
3. add up to 512 threads per block for reducing all elements in the group
~3.35x faster

Optimize GN by supporting fp16, using float for accumulating and adding more threads per block

---

source/tnn/device/metal/build_tnn_metallib.sh

修复当metal/acc下ls最后一个文件为目录时，目录名称错误，导致该目录内的metal代码文件被编译忽略的问题

[Metal][FIX] fix wrong directory in build_metal_lib

---

tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_depth_to_space.cc
tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_spacetodepth.cc

1. 修复了 issue https://github.com/Tencent/TNN/issues/960
主要是在 Fuse SpaceToDepth 和 SpaceToDepth 两个算子时， attributes 没有设置名称。

1. fix bug for SpaceToDepth and DepthToSapce;

---

third_party/flatbuffers/CMakeLists.txt
tools/onnx2tnn/onnx-converter/build.sh

1. 解决 centos 7.2 编译 flatbuffers 失败的问题
2. 优化 onnx2tnn  编译脚本

解决 centos 7.2 编译 flatbuffers 失败的问题

---

platforms/android/model_check_android.sh
tools/model_check/flags.cc
tools/model_check/flags.h
tools/model_check/main.cc

1. model_check 工具支持了指定 tnn precision（精度）的功能
目前的逻辑：
> 不指定精度：NPU:AUTO;  check output only: AUTO; else: HIGHT
> 指定精度： NPU:AUTO;  else : 使用指定的精度

1. support set tnn precision;

---

source/tnn/network/tensorrt/shape_tensor.h

When using min and max as function or variable name, windows system should be thought.

[FIX] Fix building error with CUDA on Windows

---

tools/convert2tnn/utils/run_src_model.py
tools/model_check/model_checker.cc

修复当模型转换启用--align参数时，因为blob name符号":"未统一转换成"_"，导致model check结果异常的bug。
```
model check failed! (error: code: 0x6000 msg: extend failed: mat map is not match with blobs map)
```
PS：model_check这目录代码够乱的，像赶feature搞出来的，这框架还能商用么？

Fix the bug where the model check failed due to symbol ':'

---

source/tnn/core/blob_manager.cc
source/tnn/core/default_network.cc
source/tnn/device/arm/acc/arm_reformat_layer_acc.cc
source/tnn/interpreter/net_structure.cc
source/tnn/interpreter/net_structure.h

1. 修复 reformat 单元测试不通过， #1298 
2. 调整了针对 量化模型设置 data format 的逻辑。

修复 Reformat 单测不通过

---

source/tnn/core/layer_type.cc
source/tnn/core/layer_type.h
source/tnn/device/cpu/acc/cpu_permute_layer_acc.cc
source/tnn/device/cpu/acc/cpu_splitv_layer_acc.cc
source/tnn/device/cuda/acc/cuda_permute_layer_acc.cu
source/tnn/device/cuda/acc/cuda_splitv_layer_acc.cu
source/tnn/device/x86/acc/x86_permute_layer_acc.cc
source/tnn/device/x86/acc/x86_splitv_layer_acc.cc
source/tnn/interpreter/layer_param.h
source/tnn/interpreter/tnn/layer_interpreter/permutev2_layer_interpreter.cc
source/tnn/interpreter/tnn/layer_interpreter/split_torch_layer_interpreter.cc
source/tnn/layer/permutev2_layer.cc
source/tnn/layer/split_torch_layer.cc
source/tnn/network/tensorrt/layer_builder/permute_layer_builder.cc
source/tnn/network/tensorrt/layer_builder/splitv_layer_builder.cc
source/tnn/network/torch/partitioning.cc
source/tnn/network/torch/torch_compile.cc
source/tnn/network/torch/torch_convert.cc
source/tnn/network/torch/torch_op_converter.cc
source/tnn/network/torch/torch_op_converter.h
source/tnn/network/torch/torch_optimize.cc
source/tnn/network/torch/torch_tnn_engine.cc

1. 添加aten::size，用shape，gather和unsqueeze拼起来，运行时const folder
2. split和permute根据torch的规则，增加了v2的layer type，acc部分可复用原来的
3. partition部分如果是非计算密集型子图则删除

Tnn torch subgraph debug

---

source/tnn/network/torch/torch_op_converter.cc
source/tnn/network/torch/torch_tnn_engine.cc

Add & Update TNN-Torch OP converters for Transformer Models. 1. Use matmul + Add(optional, bias) for aten::linear instead of InnerProduct to supported multi-batch linear. 2. Loosen Restrictions for ListConstruct, Size Converters. 3. Support aten::size(%in_tensor) in addition to aten::size(%in_tensor, %dim). 4 Add ListUnpack Converter.

[TORCH][FIX]Update linear,size,listConstruct,listUnpack,floordiv CVTers

---

source/tnn/network/tensorrt/shape_tensor.cc

gcc-11 now need explict `#include <limits>`, SEE http://gcc.gnu.org/gcc-11/porting_to.html

Fix gcc-11 build

---

source/tnn/network/tensorrt/layer_builder/strided_slice_v2_layer_builder.cc

In some Networks, where InferShape is skipped, when TRTNetwork::StridedSliceV2::AddToNetwork() is called, input[0], output[0] blob dims == 0. (Not set), end_dim should not be set in AddToNetwork() in these cases.

[TRT][FIX] Fix TRT StridedSliceV2 AddToNetwork Error

---

source/tnn/device/opencl/opencl_blob_converter.cc
source/tnn/device/opencl/opencl_context.cc
source/tnn/device/opencl/opencl_runtime.cc

当前方案问题：如果保存失败，每次forward都会触发保存逻辑，并且有泄漏问题。
修复方案核心：仅在构建ConvertToMat kernel阶段保存一次，解决kernel不保存引发的加载性能问题，同时对于保存失败场景，不会每次推理都尝试保存。

[opencl][fix] try save program cache

---

tools/converter/source/onnx/onnx_converter.cc
tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_batchnorm.cc
tools/onnx2tnn/src/core/onnx_utility.cc

1.   修复了由于 protobuf 升级造成的 onnx2tnn 编译失败的问题
2. related Issue： #1540

修复 protobuf 版本升级造成的 onnx2tnn 编译失败的问题

---

tools/converter/source/tflite/tflite_converter.cc

1. fix issue #1595 
2. 出现 bug 的原因是：当一层有激活函数是，SeparateActivation 方法将激活层和原始层分割开，但是InsertBlobs 添加了最后一层（也就是激活层）的输入和输出，如果激活层之前的操作没有添加到 blob 中，该层的信息就会丢失。

[CONVERTER][BUG]1. fix issue 1595;

---

test/unit_test/layer_test/test_softmax_layer.cc

[TEST] remove redundant test cases in `test_softmax_layer`

---

platforms/android/model_check_android.sh
source/tnn/optimizer/net_optimizer_dynamic_range_dequant.cc
tools/dynamic_range_quantization/main.cc

1. make model_check support dynamic range quantized model;

---

source/tnn/core/layer_type.cc
source/tnn/device/arm/acc/compute_arm82/gemm_function_fp16.cc
source/tnn/interpreter/tnn/layer_interpreter/inner_product_layer_interpreter.cc
source/tnn/optimizer/net_optimizer_dynamic_range_dequant.cc
source/tnn/optimizer/net_optimizer_dynamic_range_dequant.h
tools/dynamic_range_quantization/dynamic_range_quantization.cc
tools/dynamic_range_quantization/dynamic_range_quantization.h

1.  dynamic range quantization 添加了 inner product 层的支持；
2.  修复了 gemm fp16 在默写情况下由于累加误差比较大，导致模型不对齐的 bug；

Feature dynamic quant fc

---

platforms/mac/tnn.xcodeproj/project.pbxproj

[FIX] fix compile macos framework

---

platforms/android/model_check_android.sh
source/tnn/device/arm/acc/convolution/arm_conv_layer_acc.cc
tools/dynamic_range_quantization/dynamic_range_quantization.cc
tools/dynamic_range_quantization/dynamic_range_quantization.h
tools/dynamic_range_quantization/utils.cc
tools/dynamic_range_quantization/utils.h

1.  优化了dynamic range quantization 的逻辑，添加了根据权重分布进行过滤的逻辑；
2. dynamic range quantization 支持 fp16 的模型，进一步压缩模型大小；
3. 修复了 arm 推理 dynamic range quantization 模型（fp16， int8 模型混合）失败的 bug；
4. 修复在  model_check 中指定 reference file，但是推理时并没有实际用到的 bug；

Optimize dynamic range quantize

---

source/tnn/device/metal/acc/metal_stride_slice_v2_layer_acc.mm

1. 修复metal的stride slice算子当维度为2时的crash

[METAL] fix stride slice crach when dims is 2

---

source/tnn/device/cuda/acc/cuda_log_softmax_layer_acc.cu
source/tnn/network/tensorrt/layer_builder/log_softmax_layer_builder.cc
test/unit_test/layer_test/test_log_softmax_layer.cc

1.实现logsoftmax的cuda kernel和添加对应的trt plugin layer
2.添加logsoftmax算子在DEVICE_CUDA的单测

[CUDA][ADD] add logsoftmax operator & unittest

---

source/tnn/device/arm/acc/gradient/arm_inner_product_grad.cc

The original code forgets to multiply `sizeof(float)` when creating `RawBuffer`.

Fix a bug for RawBuffer allocation in ArmInnerProductGradOp.

---

source/tnn/core/layer_type.h

change layer id 401

---

source/tnn/core/profile.cc
source/tnn/core/profile.h

1. 在之前按照 proto 顺序打印 profiling data 的基础上，添加了按照耗时从高到低打印 profiling data 的功能

在原有的 Profiling data 的基础上新增了按照耗时排序的统计表

---

source/tnn/device/arm/acc/arm_stride_slice_layer_acc.cc
source/tnn/layer/stride_slice_v2_layer.cc

1. optimzie  stride_slice_v2 layer for arm device;
2. Unit TEST
Device:  ARM: 
```
[----------] Global test environment tear-down
[==========] 768 tests from 1 test suite ran. (2289 ms total)
[  PASSED  ] 640 tests.
[  SKIPPED ] 128 tests, listed below:
```
Device: OPENCL:
```
[----------] Global test environment tear-down
[==========] 768 tests from 1 test suite ran. (3039 ms total)
[  PASSED  ] 640 tests.
[  SKIPPED ] 128 tests, listed below:
```
3. benchmark：
找了一个测试模型，下面是对应算子的 benchmark 数据
StridedSliceV2 :  0.504  >>>>>>  StridedSliceV2  0.229

[ARM][UPD]1. optimize stride_slice_v2 layer for arm device;

---

source/tnn/device/arm/acc/gradient/arm_inner_product_grad.cc

memset(bias_grad, 0, batch * oc * sizeof(float));   => 
memset(bias_grad, 0,  oc * sizeof(float));
to void core caused by segment fault

fix: InnerProductGradient reset bias_grad

---

source/tnn/utils/cpu_utils.cc

1. 在 Apploe A16 上 CpuSupportFp16 返回false，不能正常使用 fp16 推理；

CpuSupportFp16 support Apple A16;

---

source/tnn/utils/cpu_utils.cc

1.  cpu_utils 中添加了对 Apple M2 的支持
2. CpuSupportInt8Dot 添加对 Apple A16 和 Apple M2 的支持
3. CpuSupportFp16 添加了对 Apple A16 的支持；

CpuSupportInt8Dot support Apple A16;

---

source/tnn/device/x86/acc/compute/jit/conv_gemm_config.cc
source/tnn/device/x86/acc/compute/jit/gemm_config.cc

static std::shared_ptr<jit::base_jit_kernel> g_kernel_8 [nb_kernels_m + 1][nb_kernels_n + 1];
...
using kernel_array_ptr = decltype(&g_kernel_16);
kernel_array_ptr kernel_array;
is too sophisticated to be able to compile on MacOS Clang 14,
replace it with a much simpler #define implementation.

[X86][FIX] Fix X86 jit gemm&conv_gemm Clang14 compile Error

---

source/tnn/device/cuda/CMakeLists.txt
source/tnn/device/cuda/acc/cuda_gridsample_layer_acc.cu

Added arch=compute_53 to /cuda/CMakeList.txt
Fixed std::floorf() not a member of std issue in /cuda/acc/cuda_gridsample_layer_acc.cu

Add Jetson Nano arch number 53
