- source/tnn/device/arm/acc/neon_mathfun.h
ported from https://github.com/Tencent/ncnn/commit/c35bf2f09152608858c87910763a816cb562c28a
> more stable tanh_ps

- source/tnn/utils/cpu_utils.cc
ported from https://github.com/Tencent/ncnn/commit/69e2693c87a24470a5c9ed12d13c8bced893cadd and https://github.com/Tencent/ncnn/commit/29056398901f9698edbea734ea5ef9beb21094fc
> handle GetMaxFreqOfCpu second try properly

- README_EN.md
- doc/cn/user/convert.md
- doc/en/user/convert_en.md
> [doc]update convert document

- source/tnn/device/opencl/opencl_wrapper.cc
- source/tnn/device/opencl/opencl_wrapper.h
Fix init error in some low-end devices.
> [OPENCL][CHG] remove some unused opencl api

- doc/cn/user/ncnn.md
update document of ncnn & tnn supported operations
> update document of ncnn supported operations

- tools/quantization/quantize.cc
> [TOOLS][BUG] fix quantization tool running failed

- tools/caffe2onnx/src/OPs/Tanh.py
- tools/caffe2onnx/src/OPs/__init__.py
- tools/caffe2onnx/src/caffe2onnx.py
> [TOOLS]add Tanh layer in caffe2onnx

- tools/caffe2onnx/src/OPs/Add.py
- tools/caffe2onnx/src/OPs/Power.py
- tools/caffe2onnx/src/OPs/Reshape.py
- tools/caffe2onnx/src/OPs/__init__.py
- tools/caffe2onnx/src/caffe2onnx.py
1.  在caffe2onnx的工具中支持了Power算子。
2.  修复了caffe2onnx工具中的Scale算子转换的bug。
> Feature support caffe power

- test/flags.cc
- test/flags.h
- test/test.cc
在TNNTest中支持指定输入的input_shape [feature Issue #119 ]
> Feature tnn test inputshape

- source/tnn/device/arm/acc/arm_add_layer_acc.cc
- source/tnn/device/arm/acc/arm_add_layer_acc.h
- source/tnn/device/arm/acc/arm_batch_norm_layer_acc.cc
- source/tnn/device/arm/acc/arm_batch_norm_layer_acc.h
- source/tnn/device/arm/acc/arm_binary_layer_acc.cc
- source/tnn/device/arm/acc/arm_binary_layer_acc.h
- source/tnn/device/arm/acc/arm_inner_product_layer_acc.cc
- source/tnn/device/arm/acc/arm_inner_product_layer_acc.h
- source/tnn/device/arm/acc/arm_nchw_layer_acc.cc
- source/tnn/device/arm/acc/arm_nchw_layer_acc.h
- source/tnn/device/arm/acc/arm_reformat_layer_acc.cc
- source/tnn/device/arm/acc/arm_reformat_layer_acc.h
- source/tnn/device/arm/acc/arm_unary_layer_acc.cc
- source/tnn/device/arm/acc/convolution/arm_conv_int8_layer_common.cc
- source/tnn/device/arm/acc/convolution/arm_conv_int8_layer_common.h
- source/tnn/device/arm/acc/convolution/arm_conv_layer_3x3.cc
- source/tnn/device/arm/acc/convolution/arm_conv_layer_3x3.h
- source/tnn/device/arm/acc/convolution/arm_conv_layer_common.cc
- source/tnn/device/arm/acc/convolution/arm_conv_layer_common.h
optimize reshape functions for arm layers:  move alloc params to init, reduce reshape time
> Opt reshape

- platforms/linux/CMakeLists.txt
> [TOOLS][BUG] fix model check tool build failed in linux

- doc/cn/user/convert.md
> [DOC][UPD] how to update converter's docker image

- source/tnn/device/opencl/opencl_runtime.cc
> [OPENCL][BUG] fix compile error when gcc version is below 4.9

- tools/convert2tnn/caffe_converter/caffe2tnn.py
- tools/convert2tnn/converter.py
- tools/convert2tnn/onnx_converter/align_model.py
- tools/convert2tnn/onnx_converter/onnx2tnn.py
- tools/convert2tnn/tf_converter/tf2tnn.py
- tools/convert2tnn/utils/checker.py
- tools/convert2tnn/utils/return_code.py
> [CONVERTER][ADD] add return code

- tools/onnx2tnn/src/core/onnx2tnn.cc
- tools/onnx2tnn/src/core/onnx2tnn.h
- tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_pooling.cc
- tools/onnx2tnn/src/core/onnx_remove/onnx2tnn_remove_concat.cc
- tools/onnx2tnn/src/core/onnx_utility.cc
- tools/onnx2tnn/src/core/onnx_utility.h
1. 支持了MobileNetV2-yolov3（caffe）模型的转换
2. 修复了issue 141 中描述的两个bug。
> [ONNX2TNN][BUG]1.fix issue #141;

- source/tnn/device/arm/acc/arm_pow_layer_acc.cc
> fix gnustl compile error

- source/tnn/device/metal/acc/metal_common.h
- source/tnn/device/metal/acc/metal_signed_mul_layer_acc.metal
- source/tnn/device/metal/acc/metal_signed_mul_layer_acc.mm
- test/unit_test/layer_test/test_signed_mul_layer.cc
add metal acc implementation for signedmul layer
> Feature layer signedmul

- tools/onnx2tnn/onnx-converter/CMakeLists.txt
- tools/onnx2tnn/src/core/onnx2tnn.cc
- tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_hard_swish.cc
- tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_softmax.cc
- tools/onnx2tnn/src/core/onnx_utility.cc
1. 修复了issue 162 中提到的issue。
2. 以前对HardSwitch的融合，只做了一种情况，这次补充上了另一种情况
3. 处理了将onnx2tnn中遗留的DLOG替换成LOGD。
> [ONNX2TNN][BUG]1. fix issue #162;

- examples/armlinux/src/TNNFaceDetector/TNNFaceDetector.cc
- examples/armlinux/src/TNNImageClassify/TNNImageClassify.cc
Re-implemented the demo based on the new library
> Re-implemented the demo based on the new library

- source/tnn/device/arm/acc/convolution/arm_conv_int8_layer_common.cc
- source/tnn/optimizer/net_optimizer_insert_reformat.cc
fix #175 , reformat blobs bug fiexed.
> [BUG]fix int8 reformat insert bugs, close #175

- benchmark/benchmark_armlinux/benchmark_models.sh
Completed the automated test script of armlinux benchmark
> Completed the automated test script of armlinux benchmark

- Dockerfile
1.  解决了 issue #150 的问题，不用在修改python文件
2. 将onnx的版本固定为1.6.0
> [DOCKER][UPD]1. make onnx version 1.6.0;

- examples/ios/TNNExamples.xcodeproj/project.pbxproj
- examples/ios/TNNExamples/Base.lproj/Main.storyboard
- examples/ios/TNNExamples/TNNExamplesListController.mm
- examples/ios/TNNExamples/TNNFacemeshController/TNNFacemeshController.h
- examples/ios/TNNExamples/TNNFacemeshController/TNNFacemeshController.mm
- examples/samples/BlazeFaceDetector.cc
- examples/samples/BlazeFaceDetector.h
- examples/samples/Facemesh.cc
- examples/samples/Facemesh.h
- examples/samples/ObjectDetectorSSD.cc
(1) add facemesh image demo;
(2) move the sigmoid and clip oprerations into balzeface model;
(3) fix some comments.
> add facemesh image demo

- tools/caffe2onnx/src/caffe2onnx.py
1. 解决了caffe的PReLU算子转换为onnx，某些onnx模型无法运行的bug。
> [CAFFE2ONNX][BUG] 1. fix caffe2onnx prelu converter;

- source/tnn/device/opencl/acc/opencl_concat_layer_acc.cc
> [OPENCL][OPT] change concat kernel choose strategy

- examples/android/demo/src/main/jni/cc/facedetector_jni.cc
> fix android demo memory leak

- tools/caffe2onnx/src/OPs/Slice.py
> [TOOLS][BUG] fix caffe2tnn slice layer convert error

- source/tnn/device/arm/acc/deconvolution/arm_deconv_layer_acc.cc
- source/tnn/device/arm/acc/deconvolution/arm_deconv_layer_acc.h
> [ARM][BUG] fix half-type model infer error

- source/tnn/device/arm/arm_blob_converter.cc
- test/unit_test/blob_converter_test.cc
- test/unit_test/blob_converter_test.h
> [ARM] fix inplace reverse channel

- examples/android/demo/build.gradle
> demo support armv7

- source/tnn/device/metal/acc/metal_common.metal
- source/tnn/device/metal/acc/metal_layer_acc.h
- source/tnn/device/metal/acc/metal_layer_acc.mm
- source/tnn/device/metal/acc/metal_pooling_layer_acc.metal
- source/tnn/device/metal/acc/metal_pooling_layer_acc.mm
- source/tnn/device/metal/metal_context.h
- source/tnn/device/metal/metal_context.mm
add metal kernels for average pooling when kernel size is equal to the input spatial size
> add specialized metal kernel for global average pooling

- source/tnn/device/metal/acc/metal_pooling_layer_acc.mm
fix incompatible function declaration in pool_layer_acc
> [Metal][Bug] fix incompatible function in pool_layer_acc

- source/tnn/device/arm/arm_blob_converter.cc
> [ARM][BUG] fix qunat blob scale index error

- source/tnn/device/arm/acc/convolution/arm_conv_layer_acc.cc
- source/tnn/device/arm/acc/convolution/arm_conv_layer_group.cc
- source/tnn/device/arm/acc/convolution/arm_conv_layer_group.h
- source/tnn/device/arm/arm_blob_converter.cc
- test/unit_test/layer_test/test_conv_quant_layer.cc
> 量化支持非depthwise的group卷积

- doc/cn/user/onnx2tnn.md
- doc/en/user/onnx2tnn_en.md
在 onnx2tnn readme 中添加 convertmodel.com 的信息
> add onnx2tnn web version

- source/tnn/layer/stride_slice_layer.cc
- tools/onnx2tnn/src/core/onnx2tnn.cc
- tools/onnx2tnn/src/core/onnx2tnn.h
- tools/onnx2tnn/src/core/onnx_remove/onnx2tnn_remove_dropout.cc
- tools/onnx2tnn/src/core/onnx_remove/onnx2tnn_remove_reshape.cc
- tools/onnx2tnn/src/core/onnx_remove/onnx2tnn_remove_squeeze.cc
1. 修复了 onnx2tnn 中删除 squeeze 和 unsqueeze 算子的 bug。
2. 修复了 StrideSlice 中begin 中的值为负数的情况。
> [ONNX2TNN][BUG]1. fix issue #312;

- platforms/ios/tnn.xcodeproj/project.pbxproj
修复 TNN Xcode 编译错误
由 Commit 9128495dee 引入
> fix(Build): fix xcode tnn project build issues

- source/tnn/utils/data_format_converter.h
> [BUG]1. fix issue #365;

- source/tnn/device/arm/arm_mat_converter.cc
- source/tnn/device/arm/arm_util.cc
- source/tnn/device/arm/arm_util.h
- source/tnn/device/cpu/cpu_mat_converter.cc
- source/tnn/device/cpu/cpu_mat_util.cc
- source/tnn/device/cpu/cpu_mat_util.h
- test/unit_test/mat_converter_test.cc
1. 实现YUV转BGRA；
2. 增加YUV转BGR和YUV转BGRA单元测试；
3. cvtColor性能测试结果：https://docs.qq.com/sheet/DVUxFYWtSRlZ4bUN5?tab=ey8zci
> Feature arm yuv2bgra

- .github/workflows/android-arm-cpu.yml
- .github/workflows/ios-cpu.yml
- .github/workflows/linux-x86-cpu-gcc.yml
- .github/workflows/macos-x64-cpu.yml
- .travis.yml
> Add GitHub action

- source/tnn/device/arm/acc/compute/arm32/GEMM_INT8_4X4.S
- source/tnn/device/arm/acc/compute/compute_int8.cc
> [ARM][BUG] fix armv7 float2int round error

- benchmark/benchmark_android/benchmark_models.sh
- platforms/android/test_android.sh
- source/tnn/core/instance.cc
- source/tnn/core/profile.cc
- source/tnn/core/profile.h
- source/tnn/device/huawei_npu/npu_network.cc
- source/tnn/device/huawei_npu/npu_network.h
- source/tnn/device/opencl/opencl_context.cc
- source/tnn/device/opencl/opencl_context.h
- test/unit_test/layer_test/layer_test.cc
fix issue 463, to enable profiling in Huawei NPU
> Issue #463

- source/tnn/device/arm/arm_util.cc
- source/tnn/utils/npu_common_utils.cc
- test/test_utils.cc
> [COMPILE][FIX] fix gnustl_static compile error and warning

- source/tnn/optimizer/net_optimizer_insert_fp16_reformat.cc
- source/tnn/optimizer/net_optimizer_insert_int8_reformat.cc
> [DEV][UPD] 1. Int8Reformat -> Reformat;

- source/tnn/interpreter/tnn/model_packer.cc
- tools/quantization/calibration.cc
- tools/quantization/quantize.cc
> [TOOL][ADD] add output name param support

- source/tnn/device/opencl/cl/arg.cl
- source/tnn/device/opencl/cl/signed_mul.cl
修复OpenCL fp16 select在部分华为设备编不过的问题
> [OPENCL] fix fp16 select with short condition

- source/tnn/device/opencl/opencl_context.cc
实现share command queue 依赖函数，后续需重构合并相同功能函数。
> [OPENCL][FIX] fix share opencl context

- test/unit_test/layer_test/test_reduce_op_layer.cc
> [OPENCL] reduce layer test case opt

- test/unit_test/layer_test/test_reduce_op_layer.cc
> remove reduce duplicate case

- source/tnn/device/opencl/cl/arg.cl
- source/tnn/device/opencl/cl/concat.cl
- source/tnn/device/opencl/cl/convert_to_mat.cl
- source/tnn/device/opencl/cl/convolution.cl
- source/tnn/device/opencl/cl/copy.cl
- source/tnn/device/opencl/cl/deconvolution.cl
- source/tnn/device/opencl/cl/shuffle.cl
fix IMAC(opencl version 1.2) unused variable and min function compatibility error
> [OPENCL][FIX]修复IMAC opencl 1.2 兼容错误导致无法运行unit test问题

- tools/converter/source/tflite/tflite_op_converter.cc
> 1. fix Issue #604;

- source/tnn/device/metal/acc/convolution/metal_conv_layer_acc.mm
- test/unit_test/layer_test/test_conv_layer.cc
对于metal convlayer acc，在优先级更高的acc已经建立的情况下，可能会继续尝试并选择其他低优先级acc
> Fix metal convacc selection

- source/tnn/device/opencl/cl/reduce.cl
- test/unit_test/layer_test/test_reduce_op_layer.cc
reduce multi axis 多batch计算结果不对的问题
> [OPENCL] fix reduce multi axis kernel

- source/tnn/core/blob_manager.cc
- source/tnn/core/default_network.cc
- source/tnn/core/mat.cc
- source/tnn/interpreter/ncnn/ncnn_model_interpreter.cc
- source/tnn/interpreter/ncnn/ncnn_param_utils.cc
- source/tnn/interpreter/ncnn/optimizer/expand_slice_optimizer.cc
- source/tnn/interpreter/ncnn/serializer.h
- source/tnn/interpreter/raw_buffer.cc
merge fix sign compare warning
> Fix sign compare warning

- source/tnn/device/rknpu/rknpu_network.cc
> [RKNPU][BUG] fix memleak in network init

- include/tnn/core/mat.h
- source/tnn/core/mat.cc
支持empty mat，mat部分utils接口允许传入空的mat，接口将重新为Mat分配内存。
> support empty mat

- source/tnn/core/layer_type.cc
1. 在 layer_type中添加 QuantizedUpSample.
> [QUANTIZED][BUG]1. add QuantizedUpsample(layer_type.cc);

- tools/convert2tnn/caffe_converter/caffe2tnn.py
- tools/convert2tnn/onnx_converter/onnx2tnn.py
> [CAFFE22TNN][BUG]1. fix ssd caffe model converter;

- examples/android/demo/src/main/jni/cc/objectdetectorssd_jni.cc
fix object ssd detect npc demo强制使用fp32的问题
> Patch android npu demo

- source/tnn/device/arm/acc/arm_pool_layer_acc.cc
修复arm_pool_layer bug，应该修改是类成员变量，而不是临时变量。
> fix arm_pool_layer bug

- source/tnn/layer/base_layer.cc
修复在调用 Reshape 接口时，没有正常返回错误码的问题
> [RESHAPE][BUG] fix the bug of error status

- platforms/ios/tnn.xcodeproj/project.pbxproj
- source/tnn/device/arm/acc/compute/arm32/CONV_DW_3X3_INT8_SLIDEW.S
- source/tnn/device/arm/acc/compute/compute_int8.cc
汇编优化 arm32 depthwise convolution 3x3 stride 1
> Enhance arm32 dwconv

- scripts/build_aarch64_macos.sh
- source/tnn/device/arm/acc/arm_inner_product_layer_acc.cc
- source/tnn/device/arm/acc/convolution/arm_conv_layer_acc.cc
- source/tnn/device/arm/acc/deconvolution/arm_deconv_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_batch_norm_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_binary_op_layer_acc.h
- source/tnn/device/cpu/acc/cpu_conv_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_conv_layer_acc.h
- source/tnn/device/cpu/acc/cpu_deconv_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_deconv_layer_acc.h
- source/tnn/device/cpu/acc/cpu_hdrguide_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_inner_product_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_instance_norm_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_layer_acc.h
- source/tnn/device/cpu/acc/cpu_prelu_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_scale_layer_acc.cc
- source/tnn/interpreter/layer_resource_generator.cc
- source/tnn/interpreter/layer_resource_generator.h
device cpu支持读取fp16精度的模型。
Fixes #786
> Hotfix #786

- scripts/build_ios.sh
- source/tnn/device/arm/acc/arm_arg_max_or_min_layer_acc.cc
- source/tnn/device/arm/acc/arm_instance_norm_layer_acc.cc
- source/tnn/device/arm/acc/arm_reduce_l1_layer_acc.cc
- source/tnn/device/arm/acc/arm_reduce_l2_layer_acc.cc
- source/tnn/device/arm/acc/arm_reduce_layer_acc.h
- source/tnn/device/arm/acc/arm_reduce_prod_layer_acc.cc
- source/tnn/device/arm/acc/arm_relu_layer_acc.cc
- source/tnn/device/arm/acc/arm_sign_layer_acc.cc
- source/tnn/device/arm/acc/convolution/arm_conv_layer_1x1.cc
修复build_ios.sh编译arm代码时的编译错误。通过显式指明常数类型避免构造函数选择二义性。
issue: #816
> [BUG] fix issue 816

- include/tnn/utils/dims_vector_utils.h
- source/tnn/device/cpu/acc/cpu_permute_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_permute_layer_acc.h
- source/tnn/utils/dims_vector_utils.cc
> Permute small optimization

- source/tnn/device/x86/acc/compute/jit/kernels/base_jit_kernel.h
> [BUG][X86] fix win64 jit abi error

- tools/model_check/model_checker.cc
> [TOOLS][BUG] fix model check falied when both tensor is 0

- source/tnn/device/arm/acc/convolution/arm_conv_layer_acc.cc
> [ARM][BUG] fix group conv select condition error

- source/tnn/device/arm/acc/neon_mathfun.h
port from https://github.com/Tencent/ncnn/commit/912e81d086309cc5fe7e2de8d24c11a695f7e82a
> fix tanh_ps return wrong value when input < -45

- doc/cn/user/api.md
- doc/en/user/api_en.md
- source/tnn/device/opencl/opencl_runtime.cc
> [OPENCL] update program cache doc && fix device name has space

- tools/onnx2tnn/src/core/onnx2tnn.cc
具体issue 的内容请参看： https://github.com/Tencent/TNN/issues/898
> Fix Issue 898

- tools/converter/source/onnx/onnx_conv_converter.cc
- tools/converter/source/onnx/onnx_utils.cc
- tools/onnx2tnn/src/core/layer/onnx_op_converter.h
- tools/onnx2tnn/src/core/onnx_utility.cc
修复docker protobuf相关编译错误
修复C++头文件编译错误
> [DOCKER][FIX] fix docker build error

- examples/android/demo/src/main/java/com/tencent/tnn/demo/ImageOCRDetector/ImageOCRDetectFragment.java
- examples/android/demo/src/main/java/com/tencent/tnn/demo/StreamOCRDetector/StreamOCRDetectFragment.java
> [DEMO] fix model path of android ocr demo

- doc/cn/user/compile.md
- doc/en/user/compile_en.md
- source/tnn/device/arm/arm_blob_converter.cc
- source/tnn/device/cuda/cuda_blob_converter.cc
- source/tnn/utils/blob_converter_default.cc
fix dims < 2 cause illegal memory.
> [FIX][BLOB CONVERT] fix blob convert memory illegal

- tools/convert2tnn/utils/align_model.py
- tools/converter/source/tflite/tflite_converter.cc
> 1. TFLite converter support 2 dims model;

- source/tnn/network/tensorrt/layer_builder/pad_v2_layer_builder.cc
> [FIX][CUDA] fix cuda padv2 error

- source/tnn/network/openvino/openvino_network.cc
- source/tnn/network/openvino/openvino_network.h
Add enable_const_folder on openvino network init to inherit default network.
> [FIX] fix openvino network init error without enable_const_folder

- platforms/ios/tnn.xcodeproj/project.pbxproj
- source/tnn/device/metal/acc/metal_common.h
- source/tnn/device/metal/acc/metal_tile_layer_acc.metal
- source/tnn/device/metal/acc/metal_tile_layer_acc.mm
- test/unit_test/layer_test/test_tile_layer.cc
1. metal 支持Tile 算子。
2. 在tnn.xcodeproj/project.pbxproj 添加了缺失的问题。
> Metal 支持Tile 算子

- source/tnn/device/opencl/opencl_runtime.cc
https://github.com/Tencent/TNN/issues/1036
> [OPENCL] fix compile in runtime assert

- source/tnn/device/arm/acc/convolution/arm_conv_int8_layer_common.cc
1. fix the issue: https://github.com/Tencent/TNN/issues/1046
> [ARM][BUG]1. fix out-of-range for arm conv+relu6;

- tools/quantization/scale_calculator.cc
> [QUANTIZE] quantization tools support dynamic dims

- source/tnn/utils/dims_function_utils.cc
- tools/onnx2tnn/src/core/onnx_fuse/onnx2tnn_fuse_shuffle_channel.cc
1. fix the issue: https://github.com/Tencent/TNN/issues/1055
> 修复了融合 shufflechannel 算子的 bug

- tools/quantization/calibration.cc
量化工具兼容fp16输入模型，并给出warning。
Fixes #1070
> Hotfix issue 1070

- scripts/build_android.sh
- source/tnn/device/arm/acc/arm_abs_layer_acc.cc
> fix ci check error

- source/tnn/device/opencl/cl/upsample.cl
> [OPENCL] fix upsample kernel for OpenCL 1.1

- source/tnn/utils/data_format_converter.h
- tools/convert2tnn/utils/align_model.py
- tools/converter/source/tflite/tflite_gather_converter.cc
1. TFLite converter support gather（only support dim size 2）
> TFLite Converter support gather

- include/tnn/core/macro.h
- source/tnn/device/arm/acc/arm_softmax_layer_acc.h
- test/unit_test/layer_test/test_softmax_layer.cc
> Hotfix issue 1109

- .github/workflows/linux-x86-cpu-gcc.yml
- source/tnn/device/arm/acc/arm_reformat_layer_acc.cc
- source/tnn/device/arm/acc/arm_reformat_layer_acc.h
- source/tnn/device/cpu/acc/cpu_reformat_layer_acc.cc
- source/tnn/device/x86/acc/x86_reformat_layer_acc.cc
- source/tnn/device/x86/acc/x86_reformat_layer_acc.h
- source/tnn/layer/concat_layer.cc
- source/tnn/optimizer/net_optimizer_insert_int8_reformat.cc
- tools/model_check/model_checker.cc
> [CPU][ARM][X86][BUG] fix reformat layer bug when input size > 1

- include/tnn/core/common.h
- include/tnn/core/instance.h
- source/tnn/core/abstract_network.cc
- source/tnn/core/abstract_network.h
- source/tnn/core/blob_manager.cc
- source/tnn/core/instance.cc
- source/tnn/network/torch/torch_network.cc
- source/tnn/network/torch/torch_network.h
实验结果: https://iwiki.woa.com/pages/viewpage.action?pageId=863743452
> Tnn torch share net

- source/tnn/device/metal/acc/convolution/metal_conv1d_layer_common.metal
- source/tnn/device/metal/acc/convolution/metal_conv1d_layer_common.mm
lizhenfeng   [METAL][PUD] 1.solve conv1d ios build error
> [METAL][PUD] 1.solve conv1d ios build error

- source/tnn/device/arm/acc/arm_layer_acc.cc
- tools/converter/source/tflite/tflite_argmax_or_argmin_converter.cc
- tools/converter/source/tflite/tflite_cast_converter.cc
- tools/model_check/model_checker.cc
1. TFLite converter support argmax/argmin/cast operator.
2. fix issue: https://github.com/Tencent/TNN/issues/1186
> TFLite converter support argmax/argmin/cast operator

- tools/converter/source/tflite/tflite_square_converter.cc
fix tflite square converter error
> fix tflite square converter error

- tools/model_check/main.cc
- tools/model_check/model_checker.cc
> [MODEL_CHECK][UPD] optimize the logic of align model

- source/tnn/core/const_folder.cc
- source/tnn/core/const_folder.h
- source/tnn/core/default_network.cc
- source/tnn/core/default_network.h
- source/tnn/core/instance.cc
- tools/converter/source/runtime/tnn_runtime.cc
- tools/onnx2tnn/onnx-converter/onnx2tnn_convert.cc
const folder 过滤无效的Reshape调用，减少不必要的耗时。 仅在初始化以及尺寸变化时触发Forward接口调用，进行尺寸计算。
> [const_folder] const folder check shape changed for forward

- examples/base/tnn_fps_counter.cc
> fix TNNFPSCounter error

- tools/converter/source/tflite/tflite_argmax_or_argmin_converter.cc
- tools/converter/source/tflite/tflite_cast_converter.cc
> TFLite convert fix namespace

- examples/base/tnn_sdk_sample.cc
- examples/base/tnn_sdk_sample.h
- source/tnn/device/arm/acc/arm_permute_layer_acc.cc
- source/tnn/optimizer/net_optimizer_insert_fp16_reformat.cc
修复模型中出现int32数据类型时，arm和tnn_sdk_sample的一些问题
> Fix arm int32

- tools/model_check/model_checker.cc
- tools/model_check/model_checker.h
> [MODEL_CHECK][BUG]1. DumpBlobData support int32 and int8 type;

- source/tnn/optimizer/net_optimizer_insert_fp16_reformat.cc
1. 修复了 插入 fp16 reformat 没有正确修改 format 的 bug。
> [ARM][BUG]1. fix bug for fp16 reformat;

- source/tnn/layer/tile_layer.cc
- tools/onnx2tnn/src/core/layer/onnx_op_converter.cc
1. 修复 tile 的 input 为 constant 时，output data type 推断错误的问题
2. 修复 tile 的 repeats 为 constant 时被保存为 float 类型
> [ONNX2TNN][BUG] fix the bug of tile

- source/tnn/device/arm/acc/arm_unary_layer_acc.cc
- source/tnn/device/arm/acc/compute_arm82/arm_unary_fp16_layer.h
- source/tnn/layer/stride_slice_v2_layer.cc
1. 修复 slice data_type 推导
2. 修复 sigmoid 1D 计算 bug
> Support audio model

- scripts/build_aarch64_macos.sh
- source/tnn/optimizer/net_optimizer_insert_int8_reformat.cc
> [ARM] support input to both quantize and fp32 layer

- source/tnn/utils/naive_compute.cc
> fix compile windows error

- source/tnn/device/opencl/acc/opencl_clip_layer_acc.cc
- source/tnn/device/opencl/acc/opencl_expand_layer_acc.cc
- source/tnn/device/opencl/cl/expand.cl
https://github.com/Tencent/TNN/issues/1430
> fix ocl expand kernel && clip op

- source/tnn/device/arm/acc/arm_binary_layer_acc.cc
- source/tnn/device/arm/acc/arm_layer_acc.cc
- source/tnn/device/arm/acc/compute/binary_function.cc
- source/tnn/device/arm/acc/compute_arm82/arm_binary_fp16_layer_acc.cc
- source/tnn/device/x86/acc/x86_binary_op_layer_acc.cc
- source/tnn/layer/conv1d_layer.cc
- test/unit_test/layer_test/test_conv1d_layer.cc
- test/unit_test/layer_test/test_layer_norm_layer.cc
- test/unit_test/layer_test/test_reduce_op_layer.cc
- test/unit_test/layer_test/test_splitv_layer.cc
- test/unit_test/unit_test_common.cc
1. fix #1438 
2. 修复了 ARM 端 unit test 触发的 crash，目前 ARM 端 单测都通过了
> Hotfix issue 1438

- source/tnn/device/cpu/acc/cpu_tile_layer_acc.cc
> [NAIVE][UPD]1. Cpu tile support fp16 model;

- source/tnn/network/tensorrt/layer_builder/upsample_layer_builder.cc
> fix upsample layer for align corner

- source/tnn/device/cpu/acc/compute/compute_int8.cc
- source/tnn/device/cpu/acc/compute/compute_int8.h
- source/tnn/device/cpu/acc/cpu_add_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_concat_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_conv_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_conv_layer_acc.h
- source/tnn/device/cpu/acc/cpu_inner_product_layer_acc.cc
- source/tnn/device/cpu/acc/cpu_reformat_layer_acc.cc
- source/tnn/interpreter/layer_resource.h
- source/tnn/interpreter/layer_resource_generator.cc
- source/tnn/interpreter/tnn/layer_interpreter/blob_scale_layer_interpreter.cc
- source/tnn/interpreter/tnn/layer_interpreter/conv_layer_interpreter.cc
- source/tnn/interpreter/tnn/layer_interpreter/inner_product_layer_interpreter.cc
- source/tnn/utils/blob_converter_default.cc
- source/tnn/utils/naive_compute.cc
- source/tnn/utils/naive_compute.h
- test/unit_test/unit_test_common.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_binary_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_conv_relu_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_fc_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_quantized_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_relu_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_unary_converter.cc
- tools/converter/source/tflite/tflite_conv2d_converter.cc
- tools/converter/source/tflite/tflite_fully_connected_converter.cc
- tools/converter/source/tflite/tflite_utils.cc
- tools/quantization/calibration.cc
- tools/quantization/calibration.h
1. quantized onnx convert support asymmetric quantization;
2. quantized tflite convert support asymmetric quantization;
3. fix bug for cpu inner_product forward;
4. rename sacle_bias_handle to zero_point_handle;
issue: #1465
> QAT 量化模型转换工具支持非对量化

- benchmark/benchmark_android/benchmark_models.sh
- benchmark/benchmark_armlinux/benchmark_models.sh
- benchmark/benchmark_linux/benchmark_models.sh
1.  enable  CPU device for benchmark script;
> [SCRIPT][UPD]1. enable  CPU device for benchmark script;

- source/tnn/device/x86/acc/x86_gathernd_layer_acc.cc
- source/tnn/network/openvino/custom_layer/custom_gathernd.h
- source/tnn/network/openvino/layer_builder/gathernd_layer_builder.cc
增加了 X86 和 openvino 的 gathernd 算子，计算上暂时用的都是 naive 的 kernel
> [DEV] add x86 gathernd, use naive kernel

- platforms/ios/tnn.xcodeproj/project.pbxproj
> [XCODE][BUG]1. add missing file;

- examples/ios/TNNExamples/Base.lproj/Main.storyboard
- examples/ios/TNNExamples/TNNExamplesController/TNNExamplesListController.mm
优化example的页面切换方式，更加符合iOS的交互规范
https://user-images.githubusercontent.com/4124906/148906448-8bbf1e85-abec-47e5-8ad7-0ed8555cd068.mp4
> feat: 优化example的展示逻辑，符合iOS交互规范

- source/tnn/network/coreml/coreml_model.mm
> [XCODE][UPD]1. fix bug for build ios framwork;

- platforms/android/model_check_android.sh
- tools/model_check/model_checker.cc
1. fix issue #1566 
2. 当要 dump 的数据为 fp16 时，model_check 中 data_type  设置有问题
> 1. fix bug for dump layer(fp16);

- source/tnn/device/arm/acc/arm_reduce_layer_acc.cc
- source/tnn/device/arm/arm_blob_converter.cc
- source/tnn/utils/data_format_converter.h
- tools/converter/source/tflite/tflite_op_converter.cc
* [BUG] fix get dims value bug when input is 1D or 2D in arm_reduce_layer_acc.cc.
* [BUG] fix Convert from NCHW to NHWC error when input is on arm device.
* [BUG] fix convert mat to blob bug when input is NC_INT32 on arm device.
> Bugfix from train branch

- source/tnn/device/x86/acc/x86_inner_product_layer_acc.cc
- source/tnn/device/x86/acc/x86_softmax_layer_acc.cc
fix _mm256_load_ps segmentation fault
> fix _mm256_load_ps segmentation fault

- source/tnn/device/x86/acc/x86_cpu_adapter_acc.cc
- source/tnn/device/x86/acc/x86_cpu_adapter_acc.h
- source/tnn/device/x86/x86_device.cc
- source/tnn/network/openvino/custom_layer/custom_implementation.h
- source/tnn/network/openvino/layer_builder/adapter_layer_builder.cc
- source/tnn/network/openvino/layer_builder/adapter_layer_builder.h
- source/tnn/network/openvino/layer_builder/binary_layer_builder.cc
- source/tnn/network/openvino/layer_builder/openvino_layer_builder.cc
- source/tnn/network/openvino/openvino_network.cc
- source/tnn/network/openvino/utils.cc
- source/tnn/network/openvino/utils.h
1.X86增加了一个adpater acc，没有优化的会fallback到naive的实现
2.openvino增加了adapter builder，没有写builder的会fallback到naive的实现
> Dev x86 layer adapter

- source/tnn/optimizer/net_optimizer_dynamic_range_dequant.cc
- tools/dynamic_range_quantization/dynamic_range_quantization.cc
> [UPD][DRQ] support quantizing matmul's const weight

- platforms/ios/tnn.xcodeproj/project.pbxproj
1. hotfix issue #1704 
2. add missing file for tnn xcode project;
> [iOS][UPD]1. add missing file for xcode project;

- tools/dynamic_range_quantization/utils.cc
> [DRQ][BUG]1. fix bug for max_values;

- source/tnn/device/arm/acc/compute/gemm_function.cc
- test/unit_test/third_party/googletest/googlemock/CMakeLists.txt
> Hotfix m1 build

- source/tnn/device/metal/acc/metal_add_layer_acc.metal
- source/tnn/device/metal/acc/metal_common.h
- source/tnn/device/metal/acc/metal_div_layer_acc.metal
- source/tnn/device/metal/acc/metal_mul_layer_acc.metal
- source/tnn/device/metal/acc/metal_multidir_broadcast_layer_acc.mm
- source/tnn/device/metal/acc/metal_sub_layer_acc.metal
1. fix metal binary op broadcast
> [METAL] fix metal binary op

- tools/convert2tnn/utils/align_model.py
- tools/convert2tnn/utils/fix_tnn_output.py
- tools/convert2tnn/utils/run_onnx_model.py
> fix onnxruntime inference session

- CMakeLists.txt
- source/tnn/device/x86/acc/Float4.h
- source/tnn/device/x86/acc/Float8.h
- source/tnn/device/x86/acc/compute/x86_compute.cc
- source/tnn/optimizer/graph_matcher/logger.cc
Add c++11 for windows builder;
Fix x86 compute group norm function;
> [#1775] fix x86 compute error; fix graph matcher builder on MSVC

- source/tnn/optimizer/graph_matcher/common.cc
- source/tnn/optimizer/graph_matcher/common.h
- source/tnn/optimizer/graph_matcher/graph_matcher.cc
- source/tnn/optimizer/graph_matcher/graph_matcher.h
- source/tnn/optimizer/graph_matcher/graph_parser.cc
- source/tnn/optimizer/graph_matcher/graph_parser.h
- source/tnn/optimizer/graph_matcher/graph_utils.cc
- source/tnn/optimizer/graph_matcher/graph_utils.h
- source/tnn/optimizer/graph_matcher/ir.cc
- source/tnn/optimizer/graph_matcher/ir.h
- test/matcher_test/main.cc
Graph inputs and outpus supports explicit ordering.
> Dev graph matcher

- source/tnn/device/opencl/acc/convolution/opencl_conv_layer_winograd_acc.cc
turn off winograd on some none-compute-intensive cases.
> update cl winograd filter

- source/tnn/optimizer/net_optimizer_insert_int8_reformat.cc
- source/tnn/optimizer/net_optimizer_insert_int8_reformat.h
1. 修复了之前  net_optimizer_insert_int8 的 bug
> [QUANTIZED][BUG]1. fix some bug for net_optimizer_insert_int8_reformat;

- source/tnn/core/layer_type.cc
- source/tnn/core/layer_type.h
- source/tnn/device/arm/acc/arm_glu_layer_acc.cc
- source/tnn/device/arm/acc/arm_glu_layer_acc.h
- source/tnn/device/arm/acc/compute_arm82/arm_glu_fp16_layer.cc
- source/tnn/device/cpu/acc/cpu_glu_layer_acc.cc
- source/tnn/interpreter/layer_param.h
- source/tnn/interpreter/tnn/layer_interpreter/glu_layer_interpreter.cc
- source/tnn/layer/glu_layer.cc
- test/unit_test/layer_test/test_glu_layer.cc
- tools/converter/source/onnx/onnx_pool_converter.cc
- tools/converter/source/onnx/onnx_reduce_converter.cc
- tools/converter/source/onnx/onnx_resize_converter.cc
- tools/converter/source/onnx/onnx_slice_converter.cc
- tools/converter/source/onnx/onnx_split_converter.cc
- tools/converter/source/optimizer/tnn_fuse_glu_pass.cc
- tools/converter/source/optimizer/tnn_optimizer.cc
1. 在 TNN 中增加了对 GLU 算子的支持；GLU documents: https://pytorch.org/docs/stable/generated/torch.nn.GLU.html
2. 在 arm 平台上（arm32， arm64）增加了对 GLU 算子的支持；
3. 在 unit 中添加了对 glu 算子的支持；
4. 修复了模型转换中的若干 bug；
> 增加了对 GLU 算子的支持

- tools/converter/source/onnx/onnx_pool_converter.cc
> Fix spell issue

- tools/onnx2tnn/src/core/layer/onnx_converter_split.cc
1. split 算子支持了 onnx opset 13 格式；[onnx split (opset 13)](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Split-13)
> fix split convert issue;

- tools/converter/source/onnx/onnx_batchnorm_converter.cc
- tools/converter/source/onnx/onnx_binary_converter.cc
- tools/converter/source/onnx/onnx_conv_converter.cc
- tools/converter/source/onnx/onnx_gemm_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_binary_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_conv_relu_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_fc_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_quantized_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_relu_converter.cc
- tools/converter/source/onnx/quantized_operator/onnx_int8_unary_converter.cc
- tools/converter/source/tflite/tflite_conv2d_converter.cc
- tools/converter/source/tflite/tflite_custom_converter.cc
- tools/converter/source/tflite/tflite_fully_connected_converter.cc
- tools/converter/source/tflite/tflite_prelu_converter.cc
- tools/converter/source/tflite/tflite_utils.cc
1. 将 converter 转换工具中所有创建 raw_buffer 处，添加上 raw_buffer 的 dims；
> 1. set dims for raw_buffer;

- source/tnn/device/x86/acc/x86_conv_layer_acc.cc
1. x86 device support dynamic range quant conv layer;
> x86 device support dynamic range quant conv layer;

- include/tnn/core/tnn.h
- source/tnn/core/tnn.cc
- source/tnn/core/tnn_impl.h
- source/tnn/core/tnn_impl_default.cc
- source/tnn/core/tnn_impl_default.h
- source/tnn/device/arm/acc/compute/binary_function.h
- source/tnn/device/arm/acc/gradient/arm_log_grad.cc
- source/tnn/device/rknpu/tnn_impl_rknpu.cc
- source/tnn/device/rknpu/tnn_impl_rknpu.h
- source/tnn/network/coreml/tnn_impl_coreml.h
- source/tnn/network/coreml/tnn_impl_coreml.mm
> trainning on multi objectives
